baseURL = "https://bradedwards.tech/"
title = "Brad Edwards"
theme = "salinger"

[params]

author = "Brad Edwards"
#googleAnalytics = "G-16K9W46N9Z"
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>."

DateFormat = "Jan 2006"

mainMenuSvg = '''
<svg width="40" height="40" viewBox="0 -1 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M20 7L4 7" stroke="#cccccc" stroke-width="1.5" stroke-linecap="round"></path> <path d="M20 12L4 12" stroke="#cccccc" stroke-width="1.5" stroke-linecap="round"></path> <path d="M20 17L4 17" stroke="#cccccc" stroke-width="1.5" stroke-linecap="round"></path> </g></svg>
'''

logoSvg = '''
<svg width="40" height="40" viewBox="-12 -1 36.00 36.00" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#cccccc"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M7 8L3 11.6923L7 16M17 8L21 11.6923L17 16M14 4L10 20" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
'''
logoLabel = "Think Together."

# add categories for AtomikLabs, Personal, and TechcraftingAI

mainMenuShowThemes = true
showFooterOnHomepage = true
showHeaderOnHomepage = true
showSocialOnHomepage = true
showOnlyFeaturedPost = true

filterCoverImages = true

[params.shareButtons]
  icon = "solid"
  networks = ["linkedin", "facebook", "twitter", "email"]
  size = "small"

[params.meta]
title = "Personal website of Brad Edwards, AI/ML Engineer, Vancouver, BC"
description = "Brad Edwards is an AI Engineer and MSc Computer Science with Artificial Intelligence student at the University of York."
keywords = ["Brad Edwards", "AI Engineer", "Machine Learning Engineer", "ML Engineer", "AI Engineer", "TechcraftingAI", "AtomikLabs", "University of York"]

[params.footer]
copy = 'Brad Edwards. All rights reserved.'

[[params.social]]
name = "github"
url = "https://github.com/brad-edwards"
icon = "fa-brands fa-github"
featured = true # true to be displayed in the home hero.

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/bradley-edwards-dev/"
icon = "fa-brands fa-linkedin"
featured = true # true to be displayed in the home hero.

[Menu]
[[menu.main]]
name = "Resume"
url = "/resume"
weight = 1

[[menu.main]]
name = "Dev Blog"
url = "/posts"
weight = 2

##[[menu.main]]
##name = "Projects"
##url = "/projects"
##weight = 3

[[menu.main]]
name = "Contact me"
url = "mailto:j.bradley.edwards@gmail.com"
weight = 4

[[menu.footer]]
name = "Privacy Policy"
url = "/privacy"
weight= 1 
    
[[menu.footer]]
name = "Terms and Conditions"
url = "/terms"
weight= 2

[taxonomies]
category = "categories"
lang = "langs"
tags = "tags"
tool = "tools"

[deployment]

[[deployment.targets]]
name = "production"
URL = "s3://amazon-cloudfront-secure-static-site--s3bucketroot-anx6dv0idhxt?region=us-east-1"


# the following code is mandatory for the theme to work properly.

[module]
[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"

[build]
writeStats = true
[[build.cachebusters]]
source = "assets/watching/hugo_stats\\.json"
target = "styles\\.css"
[[build.cachebusters]]
source = "(postcss|tailwind)\\.config\\.js"
target = "css"
[[build.cachebusters]]
source = "assets/.*\\.(js|ts|jsx|tsx)"
target = "js"
[[build.cachebusters]]
source = "assets/.*\\.(.*)$"
target = "$1"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = 'base16-snazzy'
